// 카테고리 VO 타입
export interface CategoryVo {
  categorySeq: string;
  shopSeq: number;
  categoryName: string;
  index: number;
  isDeleted: boolean;
  mappedCategoryCode: string;
  mappedCategoryName: string;
  mappedUptDt: string;
  isMapped: boolean;
  isHidden: boolean;
  saleDayOfWeek: number[] | null;
  saleStartTime: string;
  saleEndTime: string;
  isSaleOnHoliday: boolean;
  useTwoColumnLayout: boolean;
  isQuantitySelectable: boolean;
  isStaffCall: boolean;
  categoryDescription: string;
  isFirstOrderRequired: boolean;
  localeCategoryName: Record<string, string> | null;
  localeCategoryDescription: Record<string, string> | null;
  createDate: string | null;
  createMemberUuid: string;
  updateDate: string | null;
  updateMemberUuid: string;
  menuInfoList: MenuVo[] | null;
  localeCategoryNameStr: string;
  localeCategoryDescriptionStr: string;
  selectedLanguageCode: string;
}

// 옵션 VO 타입
export interface OptionVo {
  optionSeq: string;
  optionGroupSeq: string;
  optionName: string;
  optionPrice: number;
  index: number;
  mappedOptionCode: string;
  mappedOptionName: string;
  mappedOptionGroupCode: string;
  mappedMenuCode: string;
  mappedUptDt: string;
  localeOptionName: Record<string, string> | null;
  localeOptionDescription: Record<string, string> | null;
  createDate: string;
  createMemberUuid: string;
  updateDate: string;
  updateMemberUuid: string;
  localeOptionNameStr: string;
  localeOptionDescriptionStr: string;
  quantity: number;
  deleted: boolean;
  mapped: boolean;
  outOfStock: boolean;
}

// 옵션 그룹 VO 타입
export interface OptionGroupVo {
  description: string; // 매핑된 옵션 그룹
  optionGroupSeq: string;
  optionGroupName: string;
  menuSeq: string;
  index: number;
  mappedOptionGroupCode: string;
  mappedOptionGroupName: string;
  mappedHeadOptionGroupCode: string;
  mappedUptDt: string;
  requiredQuantity: number;
  localeOptionGroupName: Record<string, string> | null;
  localeOptionGroupDescription: Record<string, string> | null;
  createDate: string;
  createMemberUuid: string;
  updateDate: string;
  updateMemberUuid: string;
  optionList: OptionVo[];
  localeOptionGroupNameStr: string;
  localeOptionGroupDescriptionStr: string;
  deleted: boolean;
  mapped: boolean;
  optionQuantitySelectable: boolean;
  menuQuantityDependant: boolean;
  multipleSelectable: boolean;
}

// 메뉴 VO 타입
export interface MenuVo {
  menuSeq: string;
  menuName: string;
  categorySeq: string;
  menuPrice: number;
  isRecommended: boolean;
  menuDescription: string;
  isOutOfStock: boolean;
  index: number;
  mappedMenuCode: string;
  mappedMenuName: string;
  mappedCategoryCode: string;
  mappedOptionGroupCode: string;
  mappedOptionGroupCode2: string;
  mappedUptDt: string;
  isMapped: boolean;
  isHidden: boolean;
  isBest: boolean;
  isNew: boolean;
  spiceLevel: number;
  isTaxFree: boolean;
  minQuantity: number;
  touchKeyColorCode: string;
  localeMenuName: Record<string, string> | null;
  localeMenuDescription: Record<string, string> | null;
  createDate: string;
  createMemberUuid: string;
  updateDate: string;
  updateMemberUuid: string;
  optionGroupList: OptionGroupVo[] | null;
  localeMenuNameStr: string;
  localeMenuDescriptionStr: string;
  quantity: number;
  selectedOptions: OptionVo[] | null;
  totalPrice: number;
  selectedLanguageCode: string;
}

// 완전히 중첩된 Mock 데이터 구조
export const mockCategories: CategoryVo[] = [
  {
    categorySeq: '1',
    shopSeq: 0,
    categoryName: '음료',
    index: 0,
    isDeleted: false,
    mappedCategoryCode: 'CAT001',
    mappedCategoryName: 'Beverages',
    mappedUptDt: '2025-01-15 10:00:00',
    isMapped: true,
    isHidden: false,
    saleDayOfWeek: null,
    saleStartTime: '09:00',
    saleEndTime: '22:00',
    isSaleOnHoliday: true,
    useTwoColumnLayout: false,
    isQuantitySelectable: true,
    isStaffCall: false,
    categoryDescription: '시원한 음료 카테고리',
    isFirstOrderRequired: false,
    localeCategoryName: { ko: '음료', en: 'Beverages' },
    localeCategoryDescription: { ko: '시원한 음료', en: 'Cool Beverages' },
    createDate: '2025-01-01 09:00:00',
    createMemberUuid: 'c8d2e1fa-6c3f-4e2a-bb6d-7a1bfb86d210',
    updateDate: '2025-01-15 10:00:00',
    updateMemberUuid: 'u9a43b3a-4b0d-4e1b-a1d9-92f39a5b321b',
    menuInfoList: [
      {
        menuSeq: '1',
        menuName: '아메리카노',
        categorySeq: '1',
        menuPrice: 4500,
        isRecommended: true,
        menuDescription: '신선한 원두로 내린 커피',
        isOutOfStock: false,
        index: 1,
        mappedMenuCode: 'MENU001',
        mappedMenuName: 'Americano',
        mappedCategoryCode: 'CAT001',
        mappedOptionGroupCode: 'OPTG001',
        mappedOptionGroupCode2: 'OPTG001',
        mappedUptDt: '2025-11-12 10:30:00',
        isMapped: true,
        isHidden: false,
        isBest: true,
        isNew: false,
        spiceLevel: 0,
        isTaxFree: false,
        minQuantity: 1,
        touchKeyColorCode: '#FFB6C1',
        localeMenuName: { ko: '아메리카노', en: 'Americano' },
        localeMenuDescription: {
          ko: '신선한 원두 커피',
          en: 'Freshly brewed coffee',
        },
        createDate: '2025-11-12 09:00:00',
        createMemberUuid: 'c8d2e1fa-6c3f-4e2a-bb6d-7a1bfb86d210',
        updateDate: '2025-11-12 10:00:00',
        updateMemberUuid: 'u9a43b3a-4b0d-4e1b-a1d9-92f39a5b321b',
        optionGroupList: [
          {
            description: '매핑된 옵션 그룹',
            optionGroupSeq: '1',
            optionGroupName: '사이즈',
            menuSeq: '1',
            index: 0,
            mappedOptionGroupCode: 'OPTG001',
            mappedOptionGroupName: 'Size',
            mappedHeadOptionGroupCode: '',
            mappedUptDt: '2025-11-12 10:30:00',
            requiredQuantity: 1,
            localeOptionGroupName: { ko: '사이즈', en: 'Size' },
            localeOptionGroupDescription: {
              ko: '음료 사이즈를 선택하세요',
              en: 'Select beverage size',
            },
            createDate: '2025-11-12 09:00:00',
            createMemberUuid: 'c8d2e1fa-6c3f-4e2a-bb6d-7a1bfb86d210',
            updateDate: '2025-11-12 10:00:00',
            updateMemberUuid: 'u9a43b3a-4b0d-4e1b-a1d9-92f39a5b321b',
            optionList: [
              {
                optionSeq: '1',
                optionGroupSeq: '1',
                optionName: 'Regular',
                optionPrice: 0,
                index: 0,
                mappedOptionCode: 'OPT001',
                mappedOptionName: 'Regular',
                mappedOptionGroupCode: 'OPTG001',
                mappedMenuCode: 'MENU001',
                mappedUptDt: '2025-11-12 10:30:00',
                localeOptionName: { ko: '레귤러', en: 'Regular' },
                localeOptionDescription: {
                  ko: '기본 사이즈',
                  en: 'Regular size',
                },
                createDate: '2025-11-12 09:00:00',
                createMemberUuid: 'c8d2e1fa-6c3f-4e2a-bb6d-7a1bfb86d210',
                updateDate: '2025-11-12 10:00:00',
                updateMemberUuid: 'u9a43b3a-4b0d-4e1b-a1d9-92f39a5b321b',
                localeOptionNameStr: '레귤러',
                localeOptionDescriptionStr: '기본 사이즈',
                quantity: 1,
                deleted: false,
                mapped: true,
                outOfStock: false,
              },
              {
                optionSeq: '2',
                optionGroupSeq: '1',
                optionName: 'Large',
                optionPrice: 500,
                index: 1,
                mappedOptionCode: 'OPT002',
                mappedOptionName: 'Large',
                mappedOptionGroupCode: 'OPTG001',
                mappedMenuCode: 'MENU001',
                mappedUptDt: '2025-11-12 10:30:00',
                localeOptionName: { ko: '라지', en: 'Large' },
                localeOptionDescription: {
                  ko: '큰 사이즈 (+500원)',
                  en: 'Large size (+500)',
                },
                createDate: '2025-11-12 09:00:00',
                createMemberUuid: 'c8d2e1fa-6c3f-4e2a-bb6d-7a1bfb86d210',
                updateDate: '2025-11-12 10:00:00',
                updateMemberUuid: 'u9a43b3a-4b0d-4e1b-a1d9-92f39a5b321b',
                localeOptionNameStr: '라지',
                localeOptionDescriptionStr: '큰 사이즈 (+500원)',
                quantity: 1,
                deleted: false,
                mapped: true,
                outOfStock: false,
              },
              {
                optionSeq: '3',
                optionGroupSeq: '1',
                optionName: 'Extra Large',
                optionPrice: 1000,
                index: 2,
                mappedOptionCode: 'OPT003',
                mappedOptionName: 'Extra Large',
                mappedOptionGroupCode: 'OPTG001',
                mappedMenuCode: 'MENU001',
                mappedUptDt: '2025-11-12 10:30:00',
                localeOptionName: { ko: '엑스트라 라지', en: 'Extra Large' },
                localeOptionDescription: {
                  ko: '특대 사이즈 (+1000원)',
                  en: 'Extra large size (+1000)',
                },
                createDate: '2025-11-12 09:00:00',
                createMemberUuid: 'c8d2e1fa-6c3f-4e2a-bb6d-7a1bfb86d210',
                updateDate: '2025-11-12 10:00:00',
                updateMemberUuid: 'u9a43b3a-4b0d-4e1b-a1d9-92f39a5b321b',
                localeOptionNameStr: '엑스트라 라지',
                localeOptionDescriptionStr: '특대 사이즈 (+1000원)',
                quantity: 1,
                deleted: false,
                mapped: true,
                outOfStock: false,
              },
            ],
            localeOptionGroupNameStr: '사이즈',
            localeOptionGroupDescriptionStr: '음료 사이즈를 선택하세요',
            deleted: false,
            mapped: true,
            optionQuantitySelectable: false,
            menuQuantityDependant: false,
            multipleSelectable: false,
          },
          {
            description: '매핑된 옵션 그룹',
            optionGroupSeq: '2',
            optionGroupName: '온도',
            menuSeq: '1',
            index: 1,
            mappedOptionGroupCode: 'OPTG002',
            mappedOptionGroupName: 'Temperature',
            mappedHeadOptionGroupCode: '',
            mappedUptDt: '2025-11-12 10:30:00',
            requiredQuantity: 1,
            localeOptionGroupName: { ko: '온도', en: 'Temperature' },
            localeOptionGroupDescription: {
              ko: '음료 온도를 선택하세요',
              en: 'Select beverage temperature',
            },
            createDate: '2025-11-12 09:00:00',
            createMemberUuid: 'c8d2e1fa-6c3f-4e2a-bb6d-7a1bfb86d210',
            updateDate: '2025-11-12 10:00:00',
            updateMemberUuid: 'u9a43b3a-4b0d-4e1b-a1d9-92f39a5b321b',
            optionList: [
              {
                optionSeq: '4',
                optionGroupSeq: '2',
                optionName: 'Hot',
                optionPrice: 0,
                index: 0,
                mappedOptionCode: 'OPT004',
                mappedOptionName: 'Hot',
                mappedOptionGroupCode: 'OPTG002',
                mappedMenuCode: 'MENU001',
                mappedUptDt: '2025-11-12 10:30:00',
                localeOptionName: { ko: '뜨거운', en: 'Hot' },
                localeOptionDescription: {
                  ko: '뜨거운 음료',
                  en: 'Hot beverage',
                },
                createDate: '2025-11-12 09:00:00',
                createMemberUuid: 'c8d2e1fa-6c3f-4e2a-bb6d-7a1bfb86d210',
                updateDate: '2025-11-12 10:00:00',
                updateMemberUuid: 'u9a43b3a-4b0d-4e1b-a1d9-92f39a5b321b',
                localeOptionNameStr: '뜨거운',
                localeOptionDescriptionStr: '뜨거운 음료',
                quantity: 1,
                deleted: false,
                mapped: true,
                outOfStock: false,
              },
              {
                optionSeq: '5',
                optionGroupSeq: '2',
                optionName: 'Ice',
                optionPrice: 0,
                index: 1,
                mappedOptionCode: 'OPT005',
                mappedOptionName: 'Ice',
                mappedOptionGroupCode: 'OPTG002',
                mappedMenuCode: 'MENU001',
                mappedUptDt: '2025-11-12 10:30:00',
                localeOptionName: { ko: '차가운', en: 'Ice' },
                localeOptionDescription: {
                  ko: '차가운 음료',
                  en: 'Ice beverage',
                },
                createDate: '2025-11-12 09:00:00',
                createMemberUuid: 'c8d2e1fa-6c3f-4e2a-bb6d-7a1bfb86d210',
                updateDate: '2025-11-12 10:00:00',
                updateMemberUuid: 'u9a43b3a-4b0d-4e1b-a1d9-92f39a5b321b',
                localeOptionNameStr: '차가운',
                localeOptionDescriptionStr: '차가운 음료',
                quantity: 1,
                deleted: false,
                mapped: true,
                outOfStock: false,
              },
            ],
            localeOptionGroupNameStr: '온도',
            localeOptionGroupDescriptionStr: '음료 온도를 선택하세요',
            deleted: false,
            mapped: true,
            optionQuantitySelectable: false,
            menuQuantityDependant: false,
            multipleSelectable: false,
          },
          {
            description: '매핑된 옵션 그룹',
            optionGroupSeq: '3',
            optionGroupName: '추가 옵션',
            menuSeq: '1',
            index: 2,
            mappedOptionGroupCode: 'OPTG003',
            mappedOptionGroupName: 'Extra Options',
            mappedHeadOptionGroupCode: '',
            mappedUptDt: '2025-11-12 10:30:00',
            requiredQuantity: 0,
            localeOptionGroupName: { ko: '추가 옵션', en: 'Extra Options' },
            localeOptionGroupDescription: {
              ko: '추가 옵션을 선택하세요',
              en: 'Select extra options',
            },
            createDate: '2025-11-12 09:00:00',
            createMemberUuid: 'c8d2e1fa-6c3f-4e2a-bb6d-7a1bfb86d210',
            updateDate: '2025-11-12 10:00:00',
            updateMemberUuid: 'u9a43b3a-4b0d-4e1b-a1d9-92f39a5b321b',
            optionList: [
              {
                optionSeq: '6',
                optionGroupSeq: '3',
                optionName: '샷 추가',
                optionPrice: 500,
                index: 0,
                mappedOptionCode: 'OPT006',
                mappedOptionName: 'Extra Shot',
                mappedOptionGroupCode: 'OPTG003',
                mappedMenuCode: 'MENU001',
                mappedUptDt: '2025-11-12 10:30:00',
                localeOptionName: { ko: '샷 추가', en: 'Extra Shot' },
                localeOptionDescription: {
                  ko: '에스프레소 샷 추가 (+500원)',
                  en: 'Add espresso shot (+500)',
                },
                createDate: '2025-11-12 09:00:00',
                createMemberUuid: 'c8d2e1fa-6c3f-4e2a-bb6d-7a1bfb86d210',
                updateDate: '2025-11-12 10:00:00',
                updateMemberUuid: 'u9a43b3a-4b0d-4e1b-a1d9-92f39a5b321b',
                localeOptionNameStr: '샷 추가',
                localeOptionDescriptionStr: '에스프레소 샷 추가 (+500원)',
                quantity: 1,
                deleted: false,
                mapped: true,
                outOfStock: false,
              },
              {
                optionSeq: '7',
                optionGroupSeq: '3',
                optionName: '휘핑크림',
                optionPrice: 500,
                index: 1,
                mappedOptionCode: 'OPT007',
                mappedOptionName: 'Whipped Cream',
                mappedOptionGroupCode: 'OPTG003',
                mappedMenuCode: 'MENU001',
                mappedUptDt: '2025-11-12 10:30:00',
                localeOptionName: { ko: '휘핑크림', en: 'Whipped Cream' },
                localeOptionDescription: {
                  ko: '휘핑크림 추가 (+500원)',
                  en: 'Add whipped cream (+500)',
                },
                createDate: '2025-11-12 09:00:00',
                createMemberUuid: 'c8d2e1fa-6c3f-4e2a-bb6d-7a1bfb86d210',
                updateDate: '2025-11-12 10:00:00',
                updateMemberUuid: 'u9a43b3a-4b0d-4e1b-a1d9-92f39a5b321b',
                localeOptionNameStr: '휘핑크림',
                localeOptionDescriptionStr: '휘핑크림 추가 (+500원)',
                quantity: 1,
                deleted: false,
                mapped: true,
                outOfStock: false,
              },
              {
                optionSeq: '8',
                optionGroupSeq: '3',
                optionName: '시럽 추가',
                optionPrice: 300,
                index: 2,
                mappedOptionCode: 'OPT008',
                mappedOptionName: 'Syrup',
                mappedOptionGroupCode: 'OPTG003',
                mappedMenuCode: 'MENU001',
                mappedUptDt: '2025-11-12 10:30:00',
                localeOptionName: { ko: '시럽 추가', en: 'Syrup' },
                localeOptionDescription: {
                  ko: '시럽 추가 (+300원)',
                  en: 'Add syrup (+300)',
                },
                createDate: '2025-11-12 09:00:00',
                createMemberUuid: 'c8d2e1fa-6c3f-4e2a-bb6d-7a1bfb86d210',
                updateDate: '2025-11-12 10:00:00',
                updateMemberUuid: 'u9a43b3a-4b0d-4e1b-a1d9-92f39a5b321b',
                localeOptionNameStr: '시럽 추가',
                localeOptionDescriptionStr: '시럽 추가 (+300원)',
                quantity: 1,
                deleted: false,
                mapped: true,
                outOfStock: false,
              },
            ],
            localeOptionGroupNameStr: '추가 옵션',
            localeOptionGroupDescriptionStr: '추가 옵션을 선택하세요',
            deleted: false,
            mapped: true,
            optionQuantitySelectable: true,
            menuQuantityDependant: false,
            multipleSelectable: true,
          },
        ],
        localeMenuNameStr: '아메리카노',
        localeMenuDescriptionStr: '신선한 원두 커피',
        quantity: 1,
        selectedOptions: null,
        totalPrice: 4500,
        selectedLanguageCode: 'ko',
      },
      {
        menuSeq: '2',
        menuName: '카페라떼',
        categorySeq: '1',
        menuPrice: 5000,
        isRecommended: false,
        menuDescription: '부드러운 우유와 에스프레소의 조화',
        isOutOfStock: false,
        index: 2,
        mappedMenuCode: 'MENU002',
        mappedMenuName: 'Cafe Latte',
        mappedCategoryCode: 'CAT001',
        mappedOptionGroupCode: 'OPTG001',
        mappedOptionGroupCode2: 'OPTG001',
        mappedUptDt: '2025-11-12 10:30:00',
        isMapped: true,
        isHidden: false,
        isBest: false,
        isNew: true,
        spiceLevel: 0,
        isTaxFree: false,
        minQuantity: 1,
        touchKeyColorCode: '#FFB6C1',
        localeMenuName: { ko: '카페라떼', en: 'Cafe Latte' },
        localeMenuDescription: {
          ko: '부드러운 우유와 에스프레소',
          en: 'Smooth milk and espresso',
        },
        createDate: '2025-11-12 09:00:00',
        createMemberUuid: 'c8d2e1fa-6c3f-4e2a-bb6d-7a1bfb86d210',
        updateDate: '2025-11-12 10:00:00',
        updateMemberUuid: 'u9a43b3a-4b0d-4e1b-a1d9-92f39a5b321b',
        optionGroupList: null,
        localeMenuNameStr: '카페라떼',
        localeMenuDescriptionStr: '부드러운 우유와 에스프레소',
        quantity: 1,
        selectedOptions: null,
        totalPrice: 5000,
        selectedLanguageCode: 'ko',
      },
      {
        menuSeq: '5',
        menuName: '카푸치노',
        categorySeq: '1',
        menuPrice: 5500,
        isRecommended: true,
        menuDescription: '에스프레소와 스팀 우유, 거품의 완벽한 조화',
        isOutOfStock: false,
        index: 3,
        mappedMenuCode: 'MENU005',
        mappedMenuName: 'Cappuccino',
        mappedCategoryCode: 'CAT001',
        mappedOptionGroupCode: 'OPTG001',
        mappedOptionGroupCode2: 'OPTG001',
        mappedUptDt: '2025-11-12 10:30:00',
        isMapped: true,
        isHidden: false,
        isBest: false,
        isNew: false,
        spiceLevel: 0,
        isTaxFree: false,
        minQuantity: 1,
        touchKeyColorCode: '#FFB6C1',
        localeMenuName: { ko: '카푸치노', en: 'Cappuccino' },
        localeMenuDescription: {
          ko: '에스프레소와 스팀 우유',
          en: 'Espresso with steamed milk',
        },
        createDate: '2025-11-12 09:00:00',
        createMemberUuid: 'c8d2e1fa-6c3f-4e2a-bb6d-7a1bfb86d210',
        updateDate: '2025-11-12 10:00:00',
        updateMemberUuid: 'u9a43b3a-4b0d-4e1b-a1d9-92f39a5b321b',
        optionGroupList: null,
        localeMenuNameStr: '카푸치노',
        localeMenuDescriptionStr: '에스프레소와 스팀 우유',
        quantity: 1,
        selectedOptions: null,
        totalPrice: 5500,
        selectedLanguageCode: 'ko',
      },
      {
        menuSeq: '6',
        menuName: '에스프레소',
        categorySeq: '1',
        menuPrice: 3500,
        isRecommended: false,
        menuDescription: '진한 에스프레소 샷',
        isOutOfStock: false,
        index: 4,
        mappedMenuCode: 'MENU006',
        mappedMenuName: 'Espresso',
        mappedCategoryCode: 'CAT001',
        mappedOptionGroupCode: 'OPTG001',
        mappedOptionGroupCode2: 'OPTG001',
        mappedUptDt: '2025-11-12 10:30:00',
        isMapped: true,
        isHidden: false,
        isBest: false,
        isNew: false,
        spiceLevel: 0,
        isTaxFree: false,
        minQuantity: 1,
        touchKeyColorCode: '#FFB6C1',
        localeMenuName: { ko: '에스프레소', en: 'Espresso' },
        localeMenuDescription: {
          ko: '진한 에스프레소 샷',
          en: 'Strong espresso shot',
        },
        createDate: '2025-11-12 09:00:00',
        createMemberUuid: 'c8d2e1fa-6c3f-4e2a-bb6d-7a1bfb86d210',
        updateDate: '2025-11-12 10:00:00',
        updateMemberUuid: 'u9a43b3a-4b0d-4e1b-a1d9-92f39a5b321b',
        optionGroupList: null,
        localeMenuNameStr: '에스프레소',
        localeMenuDescriptionStr: '진한 에스프레소 샷',
        quantity: 1,
        selectedOptions: null,
        totalPrice: 3500,
        selectedLanguageCode: 'ko',
      },
      {
        menuSeq: '7',
        menuName: '콜드브루',
        categorySeq: '1',
        menuPrice: 6000,
        isRecommended: true,
        menuDescription: '차갑게 우려낸 부드러운 커피',
        isOutOfStock: false,
        index: 5,
        mappedMenuCode: 'MENU007',
        mappedMenuName: 'Cold Brew',
        mappedCategoryCode: 'CAT001',
        mappedOptionGroupCode: 'OPTG001',
        mappedOptionGroupCode2: 'OPTG001',
        mappedUptDt: '2025-11-12 10:30:00',
        isMapped: true,
        isHidden: false,
        isBest: true,
        isNew: true,
        spiceLevel: 0,
        isTaxFree: false,
        minQuantity: 1,
        touchKeyColorCode: '#FFB6C1',
        localeMenuName: { ko: '콜드브루', en: 'Cold Brew' },
        localeMenuDescription: {
          ko: '차갑게 우려낸 부드러운 커피',
          en: 'Smooth cold-brewed coffee',
        },
        createDate: '2025-11-12 09:00:00',
        createMemberUuid: 'c8d2e1fa-6c3f-4e2a-bb6d-7a1bfb86d210',
        updateDate: '2025-11-12 10:00:00',
        updateMemberUuid: 'u9a43b3a-4b0d-4e1b-a1d9-92f39a5b321b',
        optionGroupList: null,
        localeMenuNameStr: '콜드브루',
        localeMenuDescriptionStr: '차갑게 우려낸 부드러운 커피',
        quantity: 1,
        selectedOptions: null,
        totalPrice: 6000,
        selectedLanguageCode: 'ko',
      },
      {
        menuSeq: '8',
        menuName: '아이스티',
        categorySeq: '1',
        menuPrice: 4000,
        isRecommended: false,
        menuDescription: '시원한 복숭아 아이스티',
        isOutOfStock: false,
        index: 6,
        mappedMenuCode: 'MENU008',
        mappedMenuName: 'Iced Tea',
        mappedCategoryCode: 'CAT001',
        mappedOptionGroupCode: 'OPTG001',
        mappedOptionGroupCode2: 'OPTG001',
        mappedUptDt: '2025-11-12 10:30:00',
        isMapped: true,
        isHidden: false,
        isBest: false,
        isNew: false,
        spiceLevel: 0,
        isTaxFree: false,
        minQuantity: 1,
        touchKeyColorCode: '#FFB6C1',
        localeMenuName: { ko: '아이스티', en: 'Iced Tea' },
        localeMenuDescription: {
          ko: '시원한 복숭아 아이스티',
          en: 'Cool peach iced tea',
        },
        createDate: '2025-11-12 09:00:00',
        createMemberUuid: 'c8d2e1fa-6c3f-4e2a-bb6d-7a1bfb86d210',
        updateDate: '2025-11-12 10:00:00',
        updateMemberUuid: 'u9a43b3a-4b0d-4e1b-a1d9-92f39a5b321b',
        optionGroupList: null,
        localeMenuNameStr: '아이스티',
        localeMenuDescriptionStr: '시원한 복숭아 아이스티',
        quantity: 1,
        selectedOptions: null,
        totalPrice: 4000,
        selectedLanguageCode: 'ko',
      },
      {
        menuSeq: '9',
        menuName: '오렌지 주스',
        categorySeq: '1',
        menuPrice: 4500,
        isRecommended: false,
        menuDescription: '신선한 오렌지 주스',
        isOutOfStock: false,
        index: 7,
        mappedMenuCode: 'MENU009',
        mappedMenuName: 'Orange Juice',
        mappedCategoryCode: 'CAT001',
        mappedOptionGroupCode: 'OPTG001',
        mappedOptionGroupCode2: 'OPTG001',
        mappedUptDt: '2025-11-12 10:30:00',
        isMapped: true,
        isHidden: false,
        isBest: false,
        isNew: false,
        spiceLevel: 0,
        isTaxFree: false,
        minQuantity: 1,
        touchKeyColorCode: '#FFB6C1',
        localeMenuName: { ko: '오렌지 주스', en: 'Orange Juice' },
        localeMenuDescription: {
          ko: '신선한 오렌지 주스',
          en: 'Fresh orange juice',
        },
        createDate: '2025-11-12 09:00:00',
        createMemberUuid: 'c8d2e1fa-6c3f-4e2a-bb6d-7a1bfb86d210',
        updateDate: '2025-11-12 10:00:00',
        updateMemberUuid: 'u9a43b3a-4b0d-4e1b-a1d9-92f39a5b321b',
        optionGroupList: null,
        localeMenuNameStr: '오렌지 주스',
        localeMenuDescriptionStr: '신선한 오렌지 주스',
        quantity: 1,
        selectedOptions: null,
        totalPrice: 4500,
        selectedLanguageCode: 'ko',
      },
    ],
    localeCategoryNameStr: '음료',
    localeCategoryDescriptionStr: '시원한 음료',
    selectedLanguageCode: 'ko',
  },
  {
    categorySeq: '2',
    shopSeq: 0,
    categoryName: '메인 메뉴',
    index: 1,
    isDeleted: false,
    mappedCategoryCode: 'CAT002',
    mappedCategoryName: 'Main Menu',
    mappedUptDt: '2025-01-15 10:00:00',
    isMapped: true,
    isHidden: false,
    saleDayOfWeek: null,
    saleStartTime: '11:00',
    saleEndTime: '21:00',
    isSaleOnHoliday: true,
    useTwoColumnLayout: false,
    isQuantitySelectable: true,
    isStaffCall: false,
    categoryDescription: '메인 요리 카테고리',
    isFirstOrderRequired: false,
    localeCategoryName: { ko: '메인 메뉴', en: 'Main Menu' },
    localeCategoryDescription: { ko: '메인 요리', en: 'Main Dishes' },
    createDate: '2025-01-01 09:00:00',
    createMemberUuid: 'c8d2e1fa-6c3f-4e2a-bb6d-7a1bfb86d210',
    updateDate: '2025-01-15 10:00:00',
    updateMemberUuid: 'u9a43b3a-4b0d-4e1b-a1d9-92f39a5b321b',
    menuInfoList: [
      {
        menuSeq: '3',
        menuName: '김치찌개',
        categorySeq: '2',
        menuPrice: 12000,
        isRecommended: true,
        menuDescription: '얼큰한 김치찌개',
        isOutOfStock: false,
        index: 1,
        mappedMenuCode: 'MENU003',
        mappedMenuName: 'Kimchi Stew',
        mappedCategoryCode: 'CAT002',
        mappedOptionGroupCode: 'OPTG002',
        mappedOptionGroupCode2: 'OPTG002',
        mappedUptDt: '2025-11-12 10:30:00',
        isMapped: true,
        isHidden: false,
        isBest: true,
        isNew: false,
        spiceLevel: 3,
        isTaxFree: false,
        minQuantity: 1,
        touchKeyColorCode: '#FF6B6B',
        localeMenuName: { ko: '김치찌개', en: 'Kimchi Stew' },
        localeMenuDescription: {
          ko: '얼큰한 김치찌개',
          en: 'Spicy kimchi stew',
        },
        createDate: '2025-11-12 09:00:00',
        createMemberUuid: 'c8d2e1fa-6c3f-4e2a-bb6d-7a1bfb86d210',
        updateDate: '2025-11-12 10:00:00',
        updateMemberUuid: 'u9a43b3a-4b0d-4e1b-a1d9-92f39a5b321b',
        optionGroupList: [
          {
            description: '매핑된 옵션 그룹',
            optionGroupSeq: '4',
            optionGroupName: '양념 선택',
            menuSeq: '3',
            index: 0,
            mappedOptionGroupCode: 'OPTG004',
            mappedOptionGroupName: 'Seasoning',
            mappedHeadOptionGroupCode: '',
            mappedUptDt: '2025-11-12 10:30:00',
            requiredQuantity: 1,
            localeOptionGroupName: { ko: '양념 선택', en: 'Seasoning' },
            localeOptionGroupDescription: {
              ko: '양념을 선택하세요',
              en: 'Select seasoning',
            },
            createDate: '2025-11-12 09:00:00',
            createMemberUuid: 'c8d2e1fa-6c3f-4e2a-bb6d-7a1bfb86d210',
            updateDate: '2025-11-12 10:00:00',
            updateMemberUuid: 'u9a43b3a-4b0d-4e1b-a1d9-92f39a5b321b',
            optionList: [
              {
                optionSeq: '9',
                optionGroupSeq: '4',
                optionName: '보통',
                optionPrice: 0,
                index: 0,
                mappedOptionCode: 'OPT009',
                mappedOptionName: 'Normal',
                mappedOptionGroupCode: 'OPTG004',
                mappedMenuCode: 'MENU003',
                mappedUptDt: '2025-11-12 10:30:00',
                localeOptionName: { ko: '보통', en: 'Normal' },
                localeOptionDescription: { ko: '보통 맛', en: 'Normal taste' },
                createDate: '2025-11-12 09:00:00',
                createMemberUuid: 'c8d2e1fa-6c3f-4e2a-bb6d-7a1bfb86d210',
                updateDate: '2025-11-12 10:00:00',
                updateMemberUuid: 'u9a43b3a-4b0d-4e1b-a1d9-92f39a5b321b',
                localeOptionNameStr: '보통',
                localeOptionDescriptionStr: '보통 맛',
                quantity: 1,
                deleted: false,
                mapped: true,
                outOfStock: false,
              },
              {
                optionSeq: '10',
                optionGroupSeq: '4',
                optionName: '매운맛',
                optionPrice: 0,
                index: 1,
                mappedOptionCode: 'OPT010',
                mappedOptionName: 'Spicy',
                mappedOptionGroupCode: 'OPTG004',
                mappedMenuCode: 'MENU003',
                mappedUptDt: '2025-11-12 10:30:00',
                localeOptionName: { ko: '매운맛', en: 'Spicy' },
                localeOptionDescription: { ko: '매운 맛', en: 'Spicy taste' },
                createDate: '2025-11-12 09:00:00',
                createMemberUuid: 'c8d2e1fa-6c3f-4e2a-bb6d-7a1bfb86d210',
                updateDate: '2025-11-12 10:00:00',
                updateMemberUuid: 'u9a43b3a-4b0d-4e1b-a1d9-92f39a5b321b',
                localeOptionNameStr: '매운맛',
                localeOptionDescriptionStr: '매운 맛',
                quantity: 1,
                deleted: false,
                mapped: true,
                outOfStock: false,
              },
              {
                optionSeq: '11',
                optionGroupSeq: '4',
                optionName: '순한맛',
                optionPrice: 0,
                index: 2,
                mappedOptionCode: 'OPT011',
                mappedOptionName: 'Mild',
                mappedOptionGroupCode: 'OPTG004',
                mappedMenuCode: 'MENU003',
                mappedUptDt: '2025-11-12 10:30:00',
                localeOptionName: { ko: '순한맛', en: 'Mild' },
                localeOptionDescription: { ko: '순한 맛', en: 'Mild taste' },
                createDate: '2025-11-12 09:00:00',
                createMemberUuid: 'c8d2e1fa-6c3f-4e2a-bb6d-7a1bfb86d210',
                updateDate: '2025-11-12 10:00:00',
                updateMemberUuid: 'u9a43b3a-4b0d-4e1b-a1d9-92f39a5b321b',
                localeOptionNameStr: '순한맛',
                localeOptionDescriptionStr: '순한 맛',
                quantity: 1,
                deleted: false,
                mapped: true,
                outOfStock: false,
              },
            ],
            localeOptionGroupNameStr: '양념 선택',
            localeOptionGroupDescriptionStr: '양념을 선택하세요',
            deleted: false,
            mapped: true,
            optionQuantitySelectable: false,
            menuQuantityDependant: false,
            multipleSelectable: false,
          },
        ],
        localeMenuNameStr: '김치찌개',
        localeMenuDescriptionStr: '얼큰한 김치찌개',
        quantity: 1,
        selectedOptions: null,
        totalPrice: 12000,
        selectedLanguageCode: 'ko',
      },
      {
        menuSeq: '4',
        menuName: '삼겹살',
        categorySeq: '2',
        menuPrice: 15000,
        isRecommended: false,
        menuDescription: '신선한 삼겹살',
        isOutOfStock: false,
        index: 2,
        mappedMenuCode: 'MENU004',
        mappedMenuName: 'Pork Belly',
        mappedCategoryCode: 'CAT002',
        mappedOptionGroupCode: 'OPTG002',
        mappedOptionGroupCode2: 'OPTG002',
        mappedUptDt: '2025-11-12 10:30:00',
        isMapped: true,
        isHidden: false,
        isBest: false,
        isNew: false,
        spiceLevel: 1,
        isTaxFree: false,
        minQuantity: 1,
        touchKeyColorCode: '#FF6B6B',
        localeMenuName: { ko: '삼겹살', en: 'Pork Belly' },
        localeMenuDescription: {
          ko: '신선한 삼겹살',
          en: 'Fresh pork belly',
        },
        createDate: '2025-11-12 09:00:00',
        createMemberUuid: 'c8d2e1fa-6c3f-4e2a-bb6d-7a1bfb86d210',
        updateDate: '2025-11-12 10:00:00',
        updateMemberUuid: 'u9a43b3a-4b0d-4e1b-a1d9-92f39a5b321b',
        optionGroupList: null,
        localeMenuNameStr: '삼겹살',
        localeMenuDescriptionStr: '신선한 삼겹살',
        quantity: 1,
        selectedOptions: null,
        totalPrice: 15000,
        selectedLanguageCode: 'ko',
      },
      {
        menuSeq: '10',
        menuName: '비빔밥',
        categorySeq: '2',
        menuPrice: 11000,
        isRecommended: true,
        menuDescription: '신선한 야채와 고추장이 어우러진 비빔밥',
        isOutOfStock: false,
        index: 3,
        mappedMenuCode: 'MENU010',
        mappedMenuName: 'Bibimbap',
        mappedCategoryCode: 'CAT002',
        mappedOptionGroupCode: 'OPTG002',
        mappedOptionGroupCode2: 'OPTG002',
        mappedUptDt: '2025-11-12 10:30:00',
        isMapped: true,
        isHidden: false,
        isBest: false,
        isNew: false,
        spiceLevel: 2,
        isTaxFree: false,
        minQuantity: 1,
        touchKeyColorCode: '#FF6B6B',
        localeMenuName: { ko: '비빔밥', en: 'Bibimbap' },
        localeMenuDescription: {
          ko: '신선한 야채와 고추장',
          en: 'Fresh vegetables with gochujang',
        },
        createDate: '2025-11-12 09:00:00',
        createMemberUuid: 'c8d2e1fa-6c3f-4e2a-bb6d-7a1bfb86d210',
        updateDate: '2025-11-12 10:00:00',
        updateMemberUuid: 'u9a43b3a-4b0d-4e1b-a1d9-92f39a5b321b',
        optionGroupList: null,
        localeMenuNameStr: '비빔밥',
        localeMenuDescriptionStr: '신선한 야채와 고추장',
        quantity: 1,
        selectedOptions: null,
        totalPrice: 11000,
        selectedLanguageCode: 'ko',
      },
      {
        menuSeq: '11',
        menuName: '불고기',
        categorySeq: '2',
        menuPrice: 18000,
        isRecommended: true,
        menuDescription: '달콤한 양념의 부드러운 불고기',
        isOutOfStock: false,
        index: 4,
        mappedMenuCode: 'MENU011',
        mappedMenuName: 'Bulgogi',
        mappedCategoryCode: 'CAT002',
        mappedOptionGroupCode: 'OPTG002',
        mappedOptionGroupCode2: 'OPTG002',
        mappedUptDt: '2025-11-12 10:30:00',
        isMapped: true,
        isHidden: false,
        isBest: true,
        isNew: false,
        spiceLevel: 1,
        isTaxFree: false,
        minQuantity: 1,
        touchKeyColorCode: '#FF6B6B',
        localeMenuName: { ko: '불고기', en: 'Bulgogi' },
        localeMenuDescription: {
          ko: '달콤한 양념의 부드러운 불고기',
          en: 'Sweet marinated beef',
        },
        createDate: '2025-11-12 09:00:00',
        createMemberUuid: 'c8d2e1fa-6c3f-4e2a-bb6d-7a1bfb86d210',
        updateDate: '2025-11-12 10:00:00',
        updateMemberUuid: 'u9a43b3a-4b0d-4e1b-a1d9-92f39a5b321b',
        optionGroupList: null,
        localeMenuNameStr: '불고기',
        localeMenuDescriptionStr: '달콤한 양념의 부드러운 불고기',
        quantity: 1,
        selectedOptions: null,
        totalPrice: 18000,
        selectedLanguageCode: 'ko',
      },
      {
        menuSeq: '12',
        menuName: '된장찌개',
        categorySeq: '2',
        menuPrice: 10000,
        isRecommended: false,
        menuDescription: '구수한 된장찌개',
        isOutOfStock: false,
        index: 5,
        mappedMenuCode: 'MENU012',
        mappedMenuName: 'Doenjang Stew',
        mappedCategoryCode: 'CAT002',
        mappedOptionGroupCode: 'OPTG002',
        mappedOptionGroupCode2: 'OPTG002',
        mappedUptDt: '2025-11-12 10:30:00',
        isMapped: true,
        isHidden: false,
        isBest: false,
        isNew: false,
        spiceLevel: 2,
        isTaxFree: false,
        minQuantity: 1,
        touchKeyColorCode: '#FF6B6B',
        localeMenuName: { ko: '된장찌개', en: 'Doenjang Stew' },
        localeMenuDescription: {
          ko: '구수한 된장찌개',
          en: 'Savory soybean paste stew',
        },
        createDate: '2025-11-12 09:00:00',
        createMemberUuid: 'c8d2e1fa-6c3f-4e2a-bb6d-7a1bfb86d210',
        updateDate: '2025-11-12 10:00:00',
        updateMemberUuid: 'u9a43b3a-4b0d-4e1b-a1d9-92f39a5b321b',
        optionGroupList: null,
        localeMenuNameStr: '된장찌개',
        localeMenuDescriptionStr: '구수한 된장찌개',
        quantity: 1,
        selectedOptions: null,
        totalPrice: 10000,
        selectedLanguageCode: 'ko',
      },
      {
        menuSeq: '13',
        menuName: '제육볶음',
        categorySeq: '2',
        menuPrice: 14000,
        isRecommended: false,
        menuDescription: '매콤달콤한 제육볶음',
        isOutOfStock: false,
        index: 6,
        mappedMenuCode: 'MENU013',
        mappedMenuName: 'Jeyuk Bokkeum',
        mappedCategoryCode: 'CAT002',
        mappedOptionGroupCode: 'OPTG002',
        mappedOptionGroupCode2: 'OPTG002',
        mappedUptDt: '2025-11-12 10:30:00',
        isMapped: true,
        isHidden: false,
        isBest: false,
        isNew: true,
        spiceLevel: 3,
        isTaxFree: false,
        minQuantity: 1,
        touchKeyColorCode: '#FF6B6B',
        localeMenuName: { ko: '제육볶음', en: 'Jeyuk Bokkeum' },
        localeMenuDescription: {
          ko: '매콤달콤한 제육볶음',
          en: 'Spicy stir-fried pork',
        },
        createDate: '2025-11-12 09:00:00',
        createMemberUuid: 'c8d2e1fa-6c3f-4e2a-bb6d-7a1bfb86d210',
        updateDate: '2025-11-12 10:00:00',
        updateMemberUuid: 'u9a43b3a-4b0d-4e1b-a1d9-92f39a5b321b',
        optionGroupList: null,
        localeMenuNameStr: '제육볶음',
        localeMenuDescriptionStr: '매콤달콤한 제육볶음',
        quantity: 1,
        selectedOptions: null,
        totalPrice: 14000,
        selectedLanguageCode: 'ko',
      },
      {
        menuSeq: '14',
        menuName: '갈비탕',
        categorySeq: '2',
        menuPrice: 16000,
        isRecommended: true,
        menuDescription: '부드러운 갈비와 깔끔한 국물',
        isOutOfStock: false,
        index: 7,
        mappedMenuCode: 'MENU014',
        mappedMenuName: 'Galbitang',
        mappedCategoryCode: 'CAT002',
        mappedOptionGroupCode: 'OPTG002',
        mappedOptionGroupCode2: 'OPTG002',
        mappedUptDt: '2025-11-12 10:30:00',
        isMapped: true,
        isHidden: false,
        isBest: false,
        isNew: false,
        spiceLevel: 0,
        isTaxFree: false,
        minQuantity: 1,
        touchKeyColorCode: '#FF6B6B',
        localeMenuName: { ko: '갈비탕', en: 'Galbitang' },
        localeMenuDescription: {
          ko: '부드러운 갈비와 깔끔한 국물',
          en: 'Tender short ribs soup',
        },
        createDate: '2025-11-12 09:00:00',
        createMemberUuid: 'c8d2e1fa-6c3f-4e2a-bb6d-7a1bfb86d210',
        updateDate: '2025-11-12 10:00:00',
        updateMemberUuid: 'u9a43b3a-4b0d-4e1b-a1d9-92f39a5b321b',
        optionGroupList: null,
        localeMenuNameStr: '갈비탕',
        localeMenuDescriptionStr: '부드러운 갈비와 깔끔한 국물',
        quantity: 1,
        selectedOptions: null,
        totalPrice: 16000,
        selectedLanguageCode: 'ko',
      },
    ],
    localeCategoryNameStr: '메인 메뉴',
    localeCategoryDescriptionStr: '메인 요리',
    selectedLanguageCode: 'ko',
  },
  {
    categorySeq: '3',
    shopSeq: 0,
    categoryName: '디저트',
    index: 2,
    isDeleted: false,
    mappedCategoryCode: 'CAT003',
    mappedCategoryName: 'Desserts',
    mappedUptDt: '2025-01-15 10:00:00',
    isMapped: true,
    isHidden: false,
    saleDayOfWeek: null,
    saleStartTime: '12:00',
    saleEndTime: '22:00',
    isSaleOnHoliday: true,
    useTwoColumnLayout: false,
    isQuantitySelectable: true,
    isStaffCall: false,
    categoryDescription: '달콤한 디저트 카테고리',
    isFirstOrderRequired: false,
    localeCategoryName: { ko: '디저트', en: 'Desserts' },
    localeCategoryDescription: { ko: '달콤한 디저트', en: 'Sweet Desserts' },
    createDate: '2025-01-01 09:00:00',
    createMemberUuid: 'c8d2e1fa-6c3f-4e2a-bb6d-7a1bfb86d210',
    updateDate: '2025-01-15 10:00:00',
    updateMemberUuid: 'u9a43b3a-4b0d-4e1b-a1d9-92f39a5b321b',
    menuInfoList: [
      {
        menuSeq: '15',
        menuName: '치즈케이크',
        categorySeq: '3',
        menuPrice: 8000,
        isRecommended: true,
        menuDescription: '부드럽고 크리미한 뉴욕 치즈케이크',
        isOutOfStock: false,
        index: 1,
        mappedMenuCode: 'MENU015',
        mappedMenuName: 'Cheesecake',
        mappedCategoryCode: 'CAT003',
        mappedOptionGroupCode: 'OPTG001',
        mappedOptionGroupCode2: 'OPTG001',
        mappedUptDt: '2025-11-12 10:30:00',
        isMapped: true,
        isHidden: false,
        isBest: true,
        isNew: false,
        spiceLevel: 0,
        isTaxFree: false,
        minQuantity: 1,
        touchKeyColorCode: '#FFD700',
        localeMenuName: { ko: '치즈케이크', en: 'Cheesecake' },
        localeMenuDescription: {
          ko: '부드럽고 크리미한 뉴욕 치즈케이크',
          en: 'Smooth and creamy New York cheesecake',
        },
        createDate: '2025-11-12 09:00:00',
        createMemberUuid: 'c8d2e1fa-6c3f-4e2a-bb6d-7a1bfb86d210',
        updateDate: '2025-11-12 10:00:00',
        updateMemberUuid: 'u9a43b3a-4b0d-4e1b-a1d9-92f39a5b321b',
        optionGroupList: null,
        localeMenuNameStr: '치즈케이크',
        localeMenuDescriptionStr: '부드럽고 크리미한 뉴욕 치즈케이크',
        quantity: 1,
        selectedOptions: null,
        totalPrice: 8000,
        selectedLanguageCode: 'ko',
      },
      {
        menuSeq: '16',
        menuName: '초콜릿 케이크',
        categorySeq: '3',
        menuPrice: 7500,
        isRecommended: true,
        menuDescription: '진한 초콜릿의 달콤함',
        isOutOfStock: false,
        index: 2,
        mappedMenuCode: 'MENU016',
        mappedMenuName: 'Chocolate Cake',
        mappedCategoryCode: 'CAT003',
        mappedOptionGroupCode: 'OPTG001',
        mappedOptionGroupCode2: 'OPTG001',
        mappedUptDt: '2025-11-12 10:30:00',
        isMapped: true,
        isHidden: false,
        isBest: false,
        isNew: true,
        spiceLevel: 0,
        isTaxFree: false,
        minQuantity: 1,
        touchKeyColorCode: '#FFD700',
        localeMenuName: { ko: '초콜릿 케이크', en: 'Chocolate Cake' },
        localeMenuDescription: {
          ko: '진한 초콜릿의 달콤함',
          en: 'Rich chocolate sweetness',
        },
        createDate: '2025-11-12 09:00:00',
        createMemberUuid: 'c8d2e1fa-6c3f-4e2a-bb6d-7a1bfb86d210',
        updateDate: '2025-11-12 10:00:00',
        updateMemberUuid: 'u9a43b3a-4b0d-4e1b-a1d9-92f39a5b321b',
        optionGroupList: null,
        localeMenuNameStr: '초콜릿 케이크',
        localeMenuDescriptionStr: '진한 초콜릿의 달콤함',
        quantity: 1,
        selectedOptions: null,
        totalPrice: 7500,
        selectedLanguageCode: 'ko',
      },
      {
        menuSeq: '17',
        menuName: '아이스크림',
        categorySeq: '3',
        menuPrice: 5000,
        isRecommended: false,
        menuDescription: '시원하고 달콤한 바닐라 아이스크림',
        isOutOfStock: false,
        index: 3,
        mappedMenuCode: 'MENU017',
        mappedMenuName: 'Ice Cream',
        mappedCategoryCode: 'CAT003',
        mappedOptionGroupCode: 'OPTG001',
        mappedOptionGroupCode2: 'OPTG001',
        mappedUptDt: '2025-11-12 10:30:00',
        isMapped: true,
        isHidden: false,
        isBest: false,
        isNew: false,
        spiceLevel: 0,
        isTaxFree: false,
        minQuantity: 1,
        touchKeyColorCode: '#FFD700',
        localeMenuName: { ko: '아이스크림', en: 'Ice Cream' },
        localeMenuDescription: {
          ko: '시원하고 달콤한 바닐라 아이스크림',
          en: 'Cool and sweet vanilla ice cream',
        },
        createDate: '2025-11-12 09:00:00',
        createMemberUuid: 'c8d2e1fa-6c3f-4e2a-bb6d-7a1bfb86d210',
        updateDate: '2025-11-12 10:00:00',
        updateMemberUuid: 'u9a43b3a-4b0d-4e1b-a1d9-92f39a5b321b',
        optionGroupList: [
          {
            description: '매핑된 옵션 그룹',
            optionGroupSeq: '5',
            optionGroupName: '맛 선택',
            menuSeq: '17',
            index: 0,
            mappedOptionGroupCode: 'OPTG005',
            mappedOptionGroupName: 'Flavor',
            mappedHeadOptionGroupCode: '',
            mappedUptDt: '2025-11-12 10:30:00',
            requiredQuantity: 1,
            localeOptionGroupName: { ko: '맛 선택', en: 'Flavor' },
            localeOptionGroupDescription: {
              ko: '아이스크림 맛을 선택하세요',
              en: 'Select ice cream flavor',
            },
            createDate: '2025-11-12 09:00:00',
            createMemberUuid: 'c8d2e1fa-6c3f-4e2a-bb6d-7a1bfb86d210',
            updateDate: '2025-11-12 10:00:00',
            updateMemberUuid: 'u9a43b3a-4b0d-4e1b-a1d9-92f39a5b321b',
            optionList: [
              {
                optionSeq: '12',
                optionGroupSeq: '5',
                optionName: '바닐라',
                optionPrice: 0,
                index: 0,
                mappedOptionCode: 'OPT012',
                mappedOptionName: 'Vanilla',
                mappedOptionGroupCode: 'OPTG005',
                mappedMenuCode: 'MENU017',
                mappedUptDt: '2025-11-12 10:30:00',
                localeOptionName: { ko: '바닐라', en: 'Vanilla' },
                localeOptionDescription: {
                  ko: '클래식 바닐라',
                  en: 'Classic vanilla',
                },
                createDate: '2025-11-12 09:00:00',
                createMemberUuid: 'c8d2e1fa-6c3f-4e2a-bb6d-7a1bfb86d210',
                updateDate: '2025-11-12 10:00:00',
                updateMemberUuid: 'u9a43b3a-4b0d-4e1b-a1d9-92f39a5b321b',
                localeOptionNameStr: '바닐라',
                localeOptionDescriptionStr: '클래식 바닐라',
                quantity: 1,
                deleted: false,
                mapped: true,
                outOfStock: false,
              },
              {
                optionSeq: '13',
                optionGroupSeq: '5',
                optionName: '초콜릿',
                optionPrice: 0,
                index: 1,
                mappedOptionCode: 'OPT013',
                mappedOptionName: 'Chocolate',
                mappedOptionGroupCode: 'OPTG005',
                mappedMenuCode: 'MENU017',
                mappedUptDt: '2025-11-12 10:30:00',
                localeOptionName: { ko: '초콜릿', en: 'Chocolate' },
                localeOptionDescription: {
                  ko: '진한 초콜릿',
                  en: 'Rich chocolate',
                },
                createDate: '2025-11-12 09:00:00',
                createMemberUuid: 'c8d2e1fa-6c3f-4e2a-bb6d-7a1bfb86d210',
                updateDate: '2025-11-12 10:00:00',
                updateMemberUuid: 'u9a43b3a-4b0d-4e1b-a1d9-92f39a5b321b',
                localeOptionNameStr: '초콜릿',
                localeOptionDescriptionStr: '진한 초콜릿',
                quantity: 1,
                deleted: false,
                mapped: true,
                outOfStock: false,
              },
              {
                optionSeq: '14',
                optionGroupSeq: '5',
                optionName: '딸기',
                optionPrice: 500,
                index: 2,
                mappedOptionCode: 'OPT014',
                mappedOptionName: 'Strawberry',
                mappedOptionGroupCode: 'OPTG005',
                mappedMenuCode: 'MENU017',
                mappedUptDt: '2025-11-12 10:30:00',
                localeOptionName: { ko: '딸기', en: 'Strawberry' },
                localeOptionDescription: {
                  ko: '상큼한 딸기 (+500원)',
                  en: 'Fresh strawberry (+500)',
                },
                createDate: '2025-11-12 09:00:00',
                createMemberUuid: 'c8d2e1fa-6c3f-4e2a-bb6d-7a1bfb86d210',
                updateDate: '2025-11-12 10:00:00',
                updateMemberUuid: 'u9a43b3a-4b0d-4e1b-a1d9-92f39a5b321b',
                localeOptionNameStr: '딸기',
                localeOptionDescriptionStr: '상큼한 딸기 (+500원)',
                quantity: 1,
                deleted: false,
                mapped: true,
                outOfStock: false,
              },
            ],
            localeOptionGroupNameStr: '맛 선택',
            localeOptionGroupDescriptionStr: '아이스크림 맛을 선택하세요',
            deleted: false,
            mapped: true,
            optionQuantitySelectable: false,
            menuQuantityDependant: false,
            multipleSelectable: false,
          },
        ],
        localeMenuNameStr: '아이스크림',
        localeMenuDescriptionStr: '시원하고 달콤한 바닐라 아이스크림',
        quantity: 1,
        selectedOptions: null,
        totalPrice: 5000,
        selectedLanguageCode: 'ko',
      },
      {
        menuSeq: '18',
        menuName: '마카롱',
        categorySeq: '3',
        menuPrice: 3000,
        isRecommended: false,
        menuDescription: '예쁜 프랑스식 마카롱',
        isOutOfStock: false,
        index: 4,
        mappedMenuCode: 'MENU018',
        mappedMenuName: 'Macaron',
        mappedCategoryCode: 'CAT003',
        mappedOptionGroupCode: 'OPTG001',
        mappedOptionGroupCode2: 'OPTG001',
        mappedUptDt: '2025-11-12 10:30:00',
        isMapped: true,
        isHidden: false,
        isBest: false,
        isNew: true,
        spiceLevel: 0,
        isTaxFree: false,
        minQuantity: 1,
        touchKeyColorCode: '#FFD700',
        localeMenuName: { ko: '마카롱', en: 'Macaron' },
        localeMenuDescription: {
          ko: '예쁜 프랑스식 마카롱',
          en: 'Beautiful French macarons',
        },
        createDate: '2025-11-12 09:00:00',
        createMemberUuid: 'c8d2e1fa-6c3f-4e2a-bb6d-7a1bfb86d210',
        updateDate: '2025-11-12 10:00:00',
        updateMemberUuid: 'u9a43b3a-4b0d-4e1b-a1d9-92f39a5b321b',
        optionGroupList: null,
        localeMenuNameStr: '마카롱',
        localeMenuDescriptionStr: '예쁜 프랑스식 마카롱',
        quantity: 1,
        selectedOptions: null,
        totalPrice: 3000,
        selectedLanguageCode: 'ko',
      },
      {
        menuSeq: '19',
        menuName: '티라미수',
        categorySeq: '3',
        menuPrice: 8500,
        isRecommended: true,
        menuDescription: '이탈리아 전통 디저트 티라미수',
        isOutOfStock: false,
        index: 5,
        mappedMenuCode: 'MENU019',
        mappedMenuName: 'Tiramisu',
        mappedCategoryCode: 'CAT003',
        mappedOptionGroupCode: 'OPTG001',
        mappedOptionGroupCode2: 'OPTG001',
        mappedUptDt: '2025-11-12 10:30:00',
        isMapped: true,
        isHidden: false,
        isBest: false,
        isNew: false,
        spiceLevel: 0,
        isTaxFree: false,
        minQuantity: 1,
        touchKeyColorCode: '#FFD700',
        localeMenuName: { ko: '티라미수', en: 'Tiramisu' },
        localeMenuDescription: {
          ko: '이탈리아 전통 디저트 티라미수',
          en: 'Traditional Italian tiramisu',
        },
        createDate: '2025-11-12 09:00:00',
        createMemberUuid: 'c8d2e1fa-6c3f-4e2a-bb6d-7a1bfb86d210',
        updateDate: '2025-11-12 10:00:00',
        updateMemberUuid: 'u9a43b3a-4b0d-4e1b-a1d9-92f39a5b321b',
        optionGroupList: null,
        localeMenuNameStr: '티라미수',
        localeMenuDescriptionStr: '이탈리아 전통 디저트 티라미수',
        quantity: 1,
        selectedOptions: null,
        totalPrice: 8500,
        selectedLanguageCode: 'ko',
      },
      {
        menuSeq: '20',
        menuName: '크로와상',
        categorySeq: '3',
        menuPrice: 4000,
        isRecommended: false,
        menuDescription: '바삭하고 부드러운 프랑스식 크로와상',
        isOutOfStock: false,
        index: 6,
        mappedMenuCode: 'MENU020',
        mappedMenuName: 'Croissant',
        mappedCategoryCode: 'CAT003',
        mappedOptionGroupCode: 'OPTG001',
        mappedOptionGroupCode2: 'OPTG001',
        mappedUptDt: '2025-11-12 10:30:00',
        isMapped: true,
        isHidden: false,
        isBest: false,
        isNew: false,
        spiceLevel: 0,
        isTaxFree: false,
        minQuantity: 1,
        touchKeyColorCode: '#FFD700',
        localeMenuName: { ko: '크로와상', en: 'Croissant' },
        localeMenuDescription: {
          ko: '바삭하고 부드러운 프랑스식 크로와상',
          en: 'Crispy and soft French croissant',
        },
        createDate: '2025-11-12 09:00:00',
        createMemberUuid: 'c8d2e1fa-6c3f-4e2a-bb6d-7a1bfb86d210',
        updateDate: '2025-11-12 10:00:00',
        updateMemberUuid: 'u9a43b3a-4b0d-4e1b-a1d9-92f39a5b321b',
        optionGroupList: null,
        localeMenuNameStr: '크로와상',
        localeMenuDescriptionStr: '바삭하고 부드러운 프랑스식 크로와상',
        quantity: 1,
        selectedOptions: null,
        totalPrice: 4000,
        selectedLanguageCode: 'ko',
      },
    ],
    localeCategoryNameStr: '디저트',
    localeCategoryDescriptionStr: '달콤한 디저트',
    selectedLanguageCode: 'ko',
  },
];

// 완전한 데이터 구조를 반환하는 헬퍼 함수
export const getMockData = () => {
  return {
    categories: mockCategories,
  };
};
