import type {
  ICreateMemberRequest,
  IGetAdminShopDetail,
} from '@repo/api/types';

export const DEFAULT_SHOP_DATA: IGetAdminShopDetail = {
  shopSeq: 0,
  shopName: '',
  isActive: false,
  address1: '',
  address2: '',
  businessNumber: '',
  shopType: '',
  ownerName: '',
  isCorporate: false,
  businessType: '',
  managerName: '',
  managerPhoneNumber: '',
  shopEmail: '',
  shopPhoneNumber: '',
  isTestShop: false,
  shopBusinessCategory: '',
  shopBusinessStatus: '',
  shopCountryCode: '',
  isEarlyBetaUpdate: false,
  isEarlyUpdate: false,
  useDatadog: false,
  shopSearchName: '',
  apiToken: '',
  mappedShopCode: '',
  mappedHeadCode: '',
  createDate: '',
  createMemberUuid: '',
  updateDate: '',
  updateMemberUuid: '',
  isDeleted: false,
  useLocale: false,
  etcNote: '',
  shopCode: '',
  ownerPhoneNumber: '',
};

export const DEFAULT_MEMBER_DATA: ICreateMemberRequest = {
  memberId: '',
  shopSeq: 0,
  memberRole: 'SHOP',
  memberName: '',
  isAgreed: true,
  memberTel: '',
};
